Make the websocket client reuse the client's certificate
lxc/pylxd pull request #400
Opened 2020-05-27 19:33 UTC by pstch

This change allows to use the `events()` on remote clients, by passing the SSL certificate and keyfile from the HTTP client to to the websocket client.

I had to move the definition of `self.cert` to pick up the default certificates.

This fixes issue #381.

2021-08-16 11:26 UTC, Mohamedemad4 commented
@stgraber This PR fixes an issue I am having and currently it's not merged. is there a reason/fix i can apply to this code so it can be merged upstream?

2021-08-16 12:24 UTC, stgraber commented
@albertodonato

2021-08-16 14:53 UTC, albertodonato requested changes
Change looks good, thanks for the PR.

I just have a small nit inline.

Also, could you please rebase on current master and fix the conflict?

2021-08-16 15:34 UTC, pstch commented on pylxd/client.py
> +            ssl_options = None
Done!

2021-08-16 15:36 UTC, pstch commented
@albertodonato 

Rebased and inlined the if-statement.

However, I won't be able to test these changes for at least a few days due to some personal issues. 

I'd be glad if someone could just do a quick test before merging.

2021-08-16 21:38 UTC, Mohamedemad4 commented
I tested the changes locally and everything works great, @albertodonato  think we can merge?

2021-08-17 07:08 UTC, albertodonato commented
Thanks for the changes.

I've made CI run on the PR, and some tests also need adjusting for the websocket call change.

Also, you'll need to sign-off your commits to make the DCO check pass.

I'll merge once those issues are addressed.

2021-08-18 12:09 UTC, pstch commented
@albertodonato Oh ! I'm very sorry, I did the rebase too quickly and completely forgot about the tests. I will address that and sign the commits.

2021-08-18 15:55 UTC, pstch commented
I will investigate the failed CI run this evening.

2021-08-18 16:01 UTC, albertodonato reviewed
It seems there is still a lint error, and a couple of test failures.
Could you please check those too?

Also, a minor comment inline

2021-08-18 16:59 UTC, pstch commented on pylxd/tests/test_client.py
> +        )
Will do.

2021-08-18 21:30 UTC, pstch commented
Should be good now.

Tests were failing because the default certificates do not exist on the CI runner. I bypassed this check by forcing `Client` to use `DEFAULT_CERTS`. Since we're not testing this aspect of the `Client` class in this test, I think this is okay.

2021-08-19 09:20 UTC, albertodonato commented
did you perhaps forget to push some changes?

2021-08-20 16:01 UTC, pstch commented
I did. Sorry for that. Just pushed it.

2021-08-23 08:26 UTC, albertodonato approved these changes
+1, thanks!

2021-08-23 08:26 UTC, merged